name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v6

    - name: List Repo Files
      run: la -ltra

    - name: Execute ASCII shell script
      run: ./ascii-script.sh